### ISSUE TITLE
request: getAllPokemons

### ISSUE THREAD

**Issue by coy102** [favware/graphql-pokemon#733]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

in pokemonResolver.ts, there is getAllPokemons, but when I access [https://graphqlpokemon.favware.tech](https://graphqlpokemon.favware.tech) I can't find the query getAllPokemons

### Desired solution

Can use query getAllPokemons from [https://graphqlpokemon.favware.tech](https://graphqlpokemon.favware.tech)

### Alternatives considered

I hope I can user query getAllPokemons from GrappQL endpoint, thanks

**Comment by favna** [comment]
Use https://graphqlpokemon.favware.tech/v7, without version specifier is V6 and will be removed in due time when everyone has had time to change to a version specific variant.
