### ISSUE TITLE
request: cry url fields

### ISSUE THREAD

**Issue by castdrian** [favware/graphql-pokemon#944]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

showdown provides all cries as mp3 and ogg under 
```bash
"https://play.pokemonshowdown.com/audio/cries/:species.mp3"
"https://play.pokemonshowdown.com/audio/cries/:species.ogg"
```

### Desired solution

two additional fields on the Pokemon object, `cryMP3URL`, `cryOGGURL`

### Alternatives considered

manually formatting the url within source code, which works, but hey still would be useful

**Comment by favna** [comment]
Is it fine to provide just the mp3 files? Looks like Showdown doesn't have OGG files for Gen 8 and beyond.

**Comment by castdrian** [comment]
> Is it fine to provide just the mp3 files? Looks like Showdown doesn't have OGG files for Gen 8 and beyond.

Sure, I only listed it since they're there, I only use the mp3 files as well
