### ISSUE TITLE
request: ipa notation for base species names

### ISSUE THREAD

**Issue by castdrian** [favware/graphql-pokemon#979]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Another niche field request birthed from working on PokéDex stuff, this page has phonetic listings for Gen 1-8, those would make for a niche but useful additional field 
https://bulbapedia.bulbagarden.net/wiki/User:SnorlaxMonster/Pronunciation

### Desired solution

An additional field on the `Pokemon` object something along the lines of `pronounciation`, `ipa-notation` etc…

### Alternatives considered

Scraping the page and bundling a json document into my application

### Additional context

I’ll do the above anyway and will attach the file later  for ease of implementation if deemed useful enough

**Comment by castdrian** [comment]
gpt-4o did quick work of it ngl
[pokemon_pronunciations.json](https://github.com/user-attachments/files/15937548/pokemon_pronunciations.json)

**Comment by favna** [comment]
Added in 3680c2e48357cb9c3a49e5f71351b7aaa556a78f
